CREATE TABLE EctPais
(
    PAI_SG TEXT PRIMARY KEY NOT NULL,
    PAI_SG_ALTERNATIVA TEXT NOT NULL,
    PAI_NO_PORTUGUES TEXT NOT NULL,
    PAI_NO_INGLES TEXT NOT NULL,
    PAI_NO_FRANCES TEXT NOT NULL,
    PAI_ABREVIATURA TEXT NOT NULL
);
CREATE TABLE LOG_BAIRRO
(
    BAI_NU INTEGER PRIMARY KEY NOT NULL,
    UFE_SG TEXT NOT NULL,
    LOC_NU INTEGER NOT NULL,
    BAI_NO TEXT NOT NULL,
    BAI_NO_ABREV TEXT
);
CREATE TABLE LOG_CPC
(
    CPC_NU INTEGER PRIMARY KEY NOT NULL,
    UFE_SG TEXT NOT NULL,
    LOC_NU INTEGER NOT NULL,
    CPC_NO TEXT NOT NULL,
    CPC_ENDERECO TEXT NOT NULL,
    CEP TEXT NOT NULL
);
CREATE TABLE LOG_FAIXA_BAIRRO
(
    BAI_NU INTEGER NOT NULL,
    FCB_CEP_INI TEXT NOT NULL,
    FCB_CEP_FIM TEXT NOT NULL,
    PRIMARY KEY (BAI_NU, FCB_CEP_INI)
);
CREATE TABLE LOG_FAIXA_CPC
(
    CPC_NU INTEGER NOT NULL,
    CPC_INICIAL TEXT NOT NULL,
    CPC_FINAL TEXT NOT NULL,
    PRIMARY KEY (CPC_NU, CPC_INICIAL)
);
CREATE TABLE LOG_FAIXA_LOCALIDADE
(
    LOC_NU INTEGER NOT NULL,
    LOC_CEP_INI TEXT NOT NULL,
    LOC_CEP_FIM TEXT NOT NULL,
    PRIMARY KEY (LOC_NU, LOC_CEP_INI)
);
CREATE TABLE LOG_FAIXA_UF
(
    UFE_SG TEXT,
    UFE_CEP_INI TEXT,
    UFE_CEP_FIM TEXT,
    PRIMARY KEY (UFE_SG, UFE_CEP_INI)
);
CREATE TABLE LOG_FAIXA_UOP
(
    UOP_NU INTEGER NOT NULL,
    FNC_INICIAL INTEGER NOT NULL,
    FNC_FINAL INTEGER NOT NULL,
    PRIMARY KEY (UOP_NU, FNC_INICIAL)
);
CREATE TABLE LOG_GRANDE_USUARIO
(
    GRU_NU INTEGER PRIMARY KEY NOT NULL,
    UFE_SG TEXT NOT NULL,
    LOC_NU INTEGER NOT NULL,
    BAI_NU INTEGER NOT NULL,
    LOG_NU INTEGER,
    GRU_NO TEXT NOT NULL,
    GRU_ENDERECO TEXT NOT NULL,
    CEP TEXT NOT NULL,
    GRU_NO_ABREV TEXT
);
CREATE TABLE LOG_LOCALIDADE
(
    LOC_NU INTEGER PRIMARY KEY NOT NULL,
    UFE_SG TEXT NOT NULL,
    LOC_NO TEXT NOT NULL,
    CEP TEXT,
    LOC_IN_SIT TEXT NOT NULL,
    LOC_IN_TIPO_LOC TEXT NOT NULL,
    LOC_NU_SUB INTEGER,
    LOC_NO_ABREV TEXT,
    MUN_NU TEXT
);
CREATE TABLE LOG_LOGRADOURO
(
    LOG_NU INTEGER PRIMARY KEY NOT NULL,
    UFE_SG TEXT NOT NULL,
    LOC_NU INTEGER NOT NULL,
    BAI_NU_INI INTEGER NOT NULL,
    BAI_NU_FIM INTEGER,
    LOG_NO TEXT NOT NULL,
    LOG_COMPLEMENTO TEXT,
    CEP TEXT NOT NULL,
    TLO_TX TEXT NOT NULL,
    LOG_STA_TLO TEXT,
    LOG_NO_ABREV TEXT
);
CREATE TABLE LOG_NUM_SEC
(
    LOG_NU INTEGER PRIMARY KEY NOT NULL,
    SEC_NU_INI TEXT NOT NULL,
    SEC_NU_FIM TEXT NOT NULL,
    SEC_IN_LADO TEXT NOT NULL
);
CREATE TABLE LOG_UNID_OPER
(
    UOP_NU INTEGER PRIMARY KEY,
    UFE_SG TEXT,
    LOC_NU INTEGER,
    BAI_NU INTEGER,
    LOG_NU INTEGER,
    UOP_NO TEXT,
    UOP_ENDERECO TEXT,
    CEP TEXT,
    UOP_IN_CP TEXT,
    UOP_NO_ABREV TEXT
);
CREATE TABLE LOG_VAR_BAI
(
    BAI_NU INTEGER NOT NULL,
    VDB_NU INTEGER NOT NULL,
    VDB_TX TEXT NOT NULL,
    PRIMARY KEY (BAI_NU, VDB_NU)
);
CREATE TABLE LOG_VAR_LOC
(
    LOC_NU INTEGER NOT NULL,
    VAL_NU INTEGER NOT NULL,
    VAL_TX TEXT NOT NULL,
    PRIMARY KEY (LOC_NU, VAL_NU)
);
CREATE TABLE LOG_VAR_LOG
(
    LOG_NU INTEGER NOT NULL,
    VLO_NU INTEGER NOT NULL,
    TLO_TX TEXT NOT NULL,
    VLO_TX TEXT NOT NULL,
    PRIMARY KEY (LOG_NU, VLO_NU)
);
